export const jobs = [
    {
        "id": 1,
        "title": "Développeur Full Stack",
        "company": "TechNova Solutions",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Nous recherchons un développeur full stack pour rejoindre notre équipe.",
        "sector": "Industrie"
    },
    {
        "id": 2,
        "title": "Designer UI/UX",
        "company": "PixelCraft Studios",
        "location": "Toulouse, France",
        "type": "Temps partiel",
        "contractType": "CDD",
        "experienceRequired": "1-2 ans",
        "description": "Travaillez avec nous pour créer des interfaces utilisateurs exceptionnelles.",
        "sector": "Industrie"
    },
    {
        "id": 3,
        "title": "Chef de Projet IT",
        "company": "WebSphere Technologies",
        "location": "Paris, France",
        "type": "Freelance",
        "contractType": "Freelance",
        "experienceRequired": "5+ ans",
        "description": "Coordonnez nos projets IT et travaillez avec nos développeurs.",
        "sector": "E-commerce"
    },
    {
        "id": 4,
        "title": "Infirmier/Infirmière",
        "company": "Clinique Santé",
        "location": "Marseille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Recherchons infirmier/infirmière diplômé(e) pour rejoindre notre équipe médicale.",
        "sector": "Santé"
    },
    {
        "id": 5,
        "title": "Professeur d'Anglais",
        "company": "École Internationale",
        "location": "Nice, France",
        "type": "Temps partiel",
        "contractType": "CDD",
        "experienceRequired": "1-2 ans",
        "description": "Enseignez l'anglais aux étudiants de niveau secondaire.",
        "sector": "Education"
    },
    {
        "id": 6,
        "title": "Analyste Financier",
        "company": "Banque Centrale",
        "location": "Paris, France",
        "type": "CDI",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Analysez les données financières et fournissez des recommandations d'investissement.",
        "sector": "Banque"
    },
    {
        "id": 7,
        "title": "Responsable Marketing",
        "company": "Agence Créative",
        "location": "Bordeaux, France",
        "type": "CDD",
        "contractType": "CDD",
        "experienceRequired": "2-3 ans",
        "description": "Gérez les campagnes marketing et développez la stratégie de marque.",
        "sector": "Industrie"
    },
    {
        "id": 8,
        "title": "Chauffeur Livreur",
        "company": "Logistique Plus",
        "location": "Lille, France",
        "type": "Temps plein",
        "contractType": "Interim",
        "experienceRequired": "1-2 ans",
        "description": "Assurez la livraison des colis dans les délais impartis.",
        "sector": "Transport"
    },
    {
        "id": 9,
        "title": "Technicien Support Informatique",
        "company": "Tech Solutions",
        "location": "Lyon, France",
        "type": "Stage",
        "contractType": "Stage",
        "experienceRequired": "Débutant",
        "description": "Assurez le support informatique pour nos clients et résolvez les problèmes techniques.",
        "sector": "E-commerce"
    },
    {
        "id": 10,
        "title": "Chargé(e) de Communication",
        "company": "Fondation Humanitaire",
        "location": "Rennes, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Mettez en place des stratégies de communication pour notre fondation.",
        "sector": "Santé"
    },
    {
        "id": 11,
        "title": "Assistant Administratif",
        "company": "Société de Conseil",
        "location": "Montpellier, France",
        "type": "CDD",
        "contractType": "CDD",
        "experienceRequired": "1-2 ans",
        "description": "Soutenez notre équipe dans les tâches administratives quotidiennes.",
        "sector": "Industrie"
    },
    {
        "id": 12,
        "title": "Vendeur(se) en Boutique",
        "company": "Mode et Style",
        "location": "Lyon, France",
        "type": "Temps partiel",
        "contractType": "CDD",
        "experienceRequired": "Débutant",
        "description": "Accueillez et conseillez les clients dans notre boutique de prêt-à-porter.",
        "sector": "Agro / Textile"
    },
    {
        "id": 13,
        "title": "Ingénieur en Énergies Renouvelables",
        "company": "EcoGreen",
        "location": "Nantes, France",
        "type": "CDI",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Travaillez sur des projets d'énergie durable pour un avenir plus vert.",
        "sector": "Agriculture"
    },
    {
        "id": 14,
        "title": "Consultant en Recrutement",
        "company": "TalentSearch",
        "location": "Strasbourg, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Aidez nos clients à trouver les talents idéaux pour leurs équipes.",
        "sector": "Agro / Textile"
    },
    {
        "id": 15,
        "title": "Pharmacien(ne)",
        "company": "Pharmacie Centrale",
        "location": "Marseille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Conseillez les clients et gérez les stocks de médicaments.",
        "sector": "Santé"
    },
    {
        "id": 16,
        "title": "Assistant(e) Commercial(e)",
        "company": "Entreprise D",
        "location": "Grenoble, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "1-2 ans",
        "description": "Assistez notre équipe de vente dans le suivi des dossiers clients.",
        "sector": "E-commerce"
    },
    {
        "id": 17,
        "title": "Développeur Mobile iOS",
        "company": "Tech Innovators",
        "location": "Paris, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Développez des applications mobiles pour iOS avec notre équipe dynamique.",
        "sector": "Technologies"
    },
    {
        "id": 18,
        "title": "Directeur de Marketing Digital",
        "company": "Marketing Agency",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "5+ ans",
        "description": "Pilotez la stratégie digitale et développez des campagnes innovantes.",
        "sector": "Marketing"
    },
    {
        "id": 19,
        "title": "Consultant ERP",
        "company": "Enterprise Solutions",
        "location": "Bordeaux, France",
        "type": "Consultant",
        "contractType": "Freelance",
        "experienceRequired": "3-5 ans",
        "description": "Implémentez des solutions ERP et optimisez les systèmes d'information de nos clients.",
        "sector": "Industrie"
    },
    {
        "id": 20,
        "title": "Développeur Python",
        "company": "DataTech",
        "location": "Paris, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "1-2 ans",
        "description": "Rejoignez notre équipe pour développer des applications en Python pour des projets Big Data.",
        "sector": "Technologies"
    },
    {
        "id": 21,
        "title": "Chef de Projet Digital",
        "company": "Digital Strategies",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Gérez la planification et l'exécution de projets digitaux pour nos clients.",
        "sector": "Marketing"
    },
    {
        "id": 22,
        "title": "Médecin Généraliste",
        "company": "Clinique de Santé",
        "location": "Marseille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "5+ ans",
        "description": "Rejoignez notre clinique et fournissez des soins de santé primaires.",
        "sector": "Santé"
    },
    {
        "id": 23,
        "title": "Responsable RH",
        "company": "Human Resources Group",
        "location": "Strasbourg, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Pilotez les politiques RH, recrutez et accompagnez les talents.",
        "sector": "Ressources Humaines"
    },
    {
        "id": 24,
        "title": "Vendeur(se) de Luxe",
        "company": "Luxury Goods",
        "location": "Paris, France",
        "type": "Temps partiel",
        "contractType": "CDD",
        "experienceRequired": "1-2 ans",
        "description": "Représentez notre marque et conseillez nos clients dans le domaine du luxe.",
        "sector": "Commerce alimentaire"
    },
    {
        "id": 25,
        "title": "Data Scientist",
        "company": "AI Research Lab",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Analysez les données complexes et extrayez des informations précieuses pour la prise de décisions.",
        "sector": "Technologies"
    },
    {
        "id": 26,
        "title": "Expert en Sécurité Informatique",
        "company": "CyberDefense",
        "location": "Paris, France",
        "type": "Freelance",
        "contractType": "Freelance",
        "experienceRequired": "5+ ans",
        "description": "Protégez les systèmes d'information de nos clients contre les menaces externes.",
        "sector": "Ciberseguridad"
    },
    {
        "id": 27,
        "title": "Chargé(e) de Relations Publiques",
        "company": "PR Agency",
        "location": "Toulouse, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Développez et maintenez des relations avec les médias et les partenaires clés.",
        "sector": "Communication"
    },
    {
        "id": 28,
        "title": "Gestionnaire de Projets BTP",
        "company": "Construction Corp",
        "location": "Lille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Coordonnez les projets de construction, en assurant le respect des délais et des budgets.",
        "sector": "BTP"
    },
    {
        "id": 29,
        "title": "Analyste Financier Junior",
        "company": "Finance Group",
        "location": "Paris, France",
        "type": "Stage",
        "contractType": "Stage",
        "experienceRequired": "Débutant",
        "description": "Assistez notre équipe d'analystes financiers dans l'analyse des tendances du marché.",
        "sector": "Banque"
    },
    {
        "id": 30,
        "title": "Chef de Produit",
        "company": "Product Innovations",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Développez des produits innovants et gérez leur cycle de vie.",
        "sector": "Industrie"
    },
    {
        "id": 31,
        "title": "Développeur Frontend React",
        "company": "Frontend Experts",
        "location": "Marseille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "1-2 ans",
        "description": "Rejoignez une équipe passionnée pour développer des interfaces utilisateur réactives.",
        "sector": "Technologies"
    },
    {
        "id": 32,
        "title": "Chef de Cuisine",
        "company": "Restaurant Le Gourmet",
        "location": "Nice, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "5+ ans",
        "description": "Dirigez notre cuisine et créez des plats gastronomiques pour nos clients.",
        "sector": "Restauration"
    },
    {
        "id": 32,
        "title": "Développeur Backend Node.js",
        "company": "TechWorks",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Développez des API performantes et optimisez la gestion des données.",
        "sector": "Technologies"
    },
    {
        "id": 33,
        "title": "Chef de Projet Marketing",
        "company": "MarketLeader",
        "location": "Paris, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "5+ ans",
        "description": "Définissez et pilotez la stratégie marketing de l'entreprise.",
        "sector": "Marketing"
    },
    {
        "id": 34,
        "title": "Développeur Java",
        "company": "SoftDev Solutions",
        "location": "Bordeaux, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Rejoignez notre équipe pour développer des applications en Java.",
        "sector": "Technologies"
    },
    {
        "id": 35,
        "title": "Responsable des Ventes",
        "company": "SalesPro",
        "location": "Toulouse, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "5+ ans",
        "description": "Gérez l'équipe de vente et développez la stratégie commerciale.",
        "sector": "Commerce"
    },
    {
        "id": 36,
        "title": "Consultant en Stratégie Digitale",
        "company": "Digital Strategy Experts",
        "location": "Marseille, France",
        "type": "Consultant",
        "contractType": "Freelance",
        "experienceRequired": "3-5 ans",
        "description": "Aidez les entreprises à définir leur stratégie digitale.",
        "sector": "Marketing"
    },
    {
        "id": 37,
        "title": "Rédacteur Web SEO",
        "company": "Content Creators",
        "location": "Paris, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "1-2 ans",
        "description": "Rédigez du contenu optimisé pour le SEO pour divers sites web.",
        "sector": "Marketing"
    },
    {
        "id": 38,
        "title": "Chef de Produit Marketing",
        "company": "Product Solutions",
        "location": "Strasbourg, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Gérez le cycle de vie des produits et développez des stratégies marketing.",
        "sector": "Marketing"
    },
    {
        "id": 39,
        "title": "Contrôleur de Gestion",
        "company": "Finance Partners",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Gérez la comptabilité et le suivi financier de l'entreprise.",
        "sector": "Finance"
    },
    {
        "id": 40,
        "title": "Expert Comptable",
        "company": "Accounting Firm",
        "location": "Bordeaux, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "5+ ans",
        "description": "Fournissez des services comptables et fiscaux aux entreprises.",
        "sector": "Finance"
    },
    {
        "id": 41,
        "title": "Développeur Full Stack Python",
        "company": "CodeCraft",
        "location": "Paris, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Développez des applications web full stack en Python et JavaScript.",
        "sector": "Technologies"
    },
    {
        "id": 42,
        "title": "Chargé(e) de Recrutement",
        "company": "Human Resources Solutions",
        "location": "Strasbourg, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "1-2 ans",
        "description": "Recrutez des talents pour nos clients dans divers secteurs.",
        "sector": "Ressources Humaines"
    },
    {
        "id": 43,
        "title": "Responsable des Achats",
        "company": "Supply Chain Solutions",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Supervisez le processus d'achat et gérez les fournisseurs.",
        "sector": "Industrie"
    },
    {
        "id": 44,
        "title": "Directeur des Ressources Humaines",
        "company": "HR Consultancy",
        "location": "Marseille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "5+ ans",
        "description": "Dirigez la stratégie RH et la gestion des talents.",
        "sector": "Ressources Humaines"
    },
    {
        "id": 45,
        "title": "Développeur React Native",
        "company": "Mobile Devs",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Développez des applications mobiles avec React Native.",
        "sector": "Technologies"
    },
    {
        "id": 46,
        "title": "Community Manager",
        "company": "Digital Media Agency",
        "location": "Toulouse, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Gérez les réseaux sociaux et développez la communauté en ligne.",
        "sector": "Marketing"
    },
    {
        "id": 47,
        "title": "Consultant Business Intelligence",
        "company": "BI Experts",
        "location": "Paris, France",
        "type": "Consultant",
        "contractType": "Freelance",
        "experienceRequired": "3-5 ans",
        "description": "Analysez les données pour offrir des solutions stratégiques.",
        "sector": "Technologies"
    },
    {
        "id": 48,
        "title": "Responsable SEO",
        "company": "SEO Solutions",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Développez et exécutez des stratégies SEO pour améliorer la visibilité des sites web.",
        "sector": "Marketing"
    },
    {
        "id": 49,
        "title": "Chef de Projet Digital",
        "company": "Digital Solutions",
        "location": "Paris, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Supervisez des projets digitaux et assurez leur succès.",
        "sector": "Marketing"
    },
    {
        "id": 50,
        "title": "Technicien Maintenance Informatique",
        "company": "Tech Solutions",
        "location": "Toulouse, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Effectuez la maintenance et le dépannage des équipements informatiques.",
        "sector": "Technologies"
    },
    {
        "id": 51,
        "title": "Architecte Logiciel",
        "company": "Software Architects",
        "location": "Marseille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "5+ ans",
        "description": "Concevez des architectures logicielles robustes pour des projets complexes.",
        "sector": "Technologies"
    },
    {
        "id": 52,
        "title": "Assistant(e) RH",
        "company": "HR Partners",
        "location": "Paris, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "1-2 ans",
        "description": "Assistez l'équipe RH dans la gestion des recrutements et des dossiers du personnel.",
        "sector": "Ressources Humaines"
    },
    {
        "id": 53,
        "title": "Consultant en Transformation Digitale",
        "company": "Transformation Group",
        "location": "Lyon, France",
        "type": "Consultant",
        "contractType": "Freelance",
        "experienceRequired": "5+ ans",
        "description": "Accompagnez les entreprises dans leur transformation numérique.",
        "sector": "Technologies"
    },
    {
        "id": 54,
        "title": "Chef de Projet IT",
        "company": "Tech Innovators",
        "location": "Marseille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Gérez des projets informatiques et assurez leur mise en œuvre.",
        "sector": "Technologies"
    },
    {
        "id": 55,
        "title": "Développeur iOS",
        "company": "Mobile Devs",
        "location": "Paris, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Développez des applications iOS innovantes et performantes.",
        "sector": "Technologies"
    },
    {
        "id": 56,
        "title": "Responsable Commercial",
        "company": "Sales Agency",
        "location": "Strasbourg, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Développez et implémentez des stratégies commerciales pour l'entreprise.",
        "sector": "Commerce"
    },
    {
        "id": 57,
        "title": "Développeur Node.js",
        "company": "CodeLab",
        "location": "Lyon, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "2-3 ans",
        "description": "Développez des applications et des API performantes en Node.js.",
        "sector": "Technologies"
    },
    {
        "id": 58,
        "title": "Consultant SAP",
        "company": "SAP Experts",
        "location": "Paris, France",
        "type": "Consultant",
        "contractType": "Freelance",
        "experienceRequired": "5+ ans",
        "description": "Accompagnez les entreprises dans l'implémentation de solutions SAP.",
        "sector": "Technologies"
    },
    {
        "id": 59,
        "title": "Responsable Marketing Digital",
        "company": "Digital Strategies",
        "location": "Marseille, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "3-5 ans",
        "description": "Concevez et pilotez la stratégie digitale pour augmenter la visibilité de l'entreprise.",
        "sector": "Marketing"
    },
    {
        "id": 60,
        "title": "Data Analyst",
        "company": "Data Experts",
        "location": "Bordeaux, France",
        "type": "Temps plein",
        "contractType": "CDI",
        "experienceRequired": "1-2 ans",
        "description": "Analysez les données pour fournir des insights stratégiques à l'entreprise.",
        "sector": "Technologies"
    }
]
