export const posts = [
    {
      url: "https://demoapus1.com/jobtex-new/secteurs-qui-recrutent-en-2024/",
      image: "https://demoapus1.com/jobtex-new/wp-content/uploads/elementor/thumbs/blog7-qgciz2qa69l7mva13ub3lxnmfuhax9klqo3wp1pfis.jpg",
      title: "Secteurs qui recrutent en 2024",
      category: "Emploi",
      categoryUrl: "https://demoapus1.com/jobtex-new/category/emploi/",
      author: "admin",
      authorUrl: "#",
      date: "15 Février, 2024",
    },
    {
      url: "https://demoapus1.com/jobtex-new/les-meilleures-aides-pour-creer-son-entreprise/",
      image: "https://demoapus1.com/jobtex-new/wp-content/uploads/elementor/thumbs/blog6-qgciz2qa69l7mva13ub3lxnmfuhax9klqo3wp1pfis.jpg",
      title: "Les meilleures aides pour créer son entreprise",
      category: "Création d\"Entreprise",
      categoryUrl: "https://demoapus1.com/jobtex-new/category/creation-entreprise/",
      author: "admin",
      authorUrl: "#",
      date: "10 Mars, 2024",
    },
    {
      url: "https://demoapus1.com/jobtex-new/comment-faire-face-aux-changements-economiques/",
      image: "https://demoapus1.com/jobtex-new/wp-content/uploads/elementor/thumbs/blog5-qgciz1sfzfjxb9be9bwh1fw5uglxpkgvejgf7rqtp0.jpg",
      title: "Comment faire face aux changements économiques",
      category: "Économie",
      categoryUrl: "https://demoapus1.com/jobtex-new/category/economie/",
      author: "admin",
      authorUrl: "#",
      date: "5 Avril, 2024",
    },
    {
      url: "https://demoapus1.com/jobtex-new/conseils-pour-ameliorer-son-cv-et-attirer-les-recruteurs/",
      image: "https://demoapus1.com/jobtex-new/wp-content/uploads/elementor/thumbs/blog4-qgciz2qa69l7mva13ub3lxnmfuhax9klqo3wp1pfis.jpg",
      title: "Conseils pour améliorer son CV et attirer les recruteurs",
      category: "Emploi",
      categoryUrl: "https://demoapus1.com/jobtex-new/category/emploi/",
      author: "admin",
      authorUrl: "#",
      date: "12 Mai, 2024",
    },
    {
      url: "https://demoapus1.com/jobtex-new/etapes-pour-lancer-une-startup/",
      image: "https://demoapus1.com/jobtex-new/wp-content/uploads/elementor/thumbs/blog3-qgciz2qa69l7mva13ub3lxnmfuhax9klqo3wp1pfis.jpg",
      title: "Les étapes pour lancer une startup",
      category: "Entrepreneuriat",
      categoryUrl: "https://demoapus1.com/jobtex-new/category/entrepreneuriat/",
      author: "admin",
      authorUrl: "#",
      date: "8 Juin, 2024",
    },
];
