export const pageTitles = {
    home: "Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    aboutUs: "Nous Sommes | Agence Intérimaire et Solutions RH",
    howItWorks: "Comment ça marche ? | Agence Intérimaire et Solutions RH",
    secteursActivite: "Secteurs d'Activité | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    jobOffers: "Dernières offres d'emploi | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    jobsByLocation: "Emplois par Localisation | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    agences: "Nos Agences | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    partenaires: "Partenaires | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    candidatures: "Candidatures | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    jobPage: "Offres d'emploi | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    contact: "Contactez-nous | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    cgu: "CGU | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    mentionsLegales: "Mentions Légales | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    politiqueConfidentialite: "Politique de Confidentialité | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
    politiqueGestionCookies: "Politique de Gestion des Cookies | Keys - Intérim & Recrutement | Agence Intérimaire et Solutions RH",
};